=== INCF/apine/apine.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#", 
  "$id": "https://github.com/INCF/apine/blob/master/apine.schema.json", 
  "type": "object", 
  "additionalProperties": false, 
  "properties": {
    "dataset": {
      "$id": "/properties/dataset", 
      "minLength": 1,
      "type": "string", 
      "title": "dataset", 
			"required": true,
      "description": "The parent" 
    },
    "participant": {
      "$id": "/properties/participant", 
      "type": "string", 
			"required": false,
      "title": "participant", 
      "description": "The corresponding participant"
    }, 
    "session": {
      "$id": "/properties/session", 
      "type": "string", 
			"required": false,
      "title": "session",
      "description": "The corresponding session"
    },
    "modality": {
      "$id": "/properties/modality", 
      "type": "string", 
			"required": false,
      "title": "modality", 
      "description": "The corresponding modality", 
      "examples": [
        "func",
				"anat",
				"dwi",
				"fmap"
      ]
    }, 
    "filename": {
      "$id": "/properties/filename", 
      "type": "string", 
			"required": true,
      "title": "filename", 
      "description": "The filename being described"
    }, 
    "filename_keys": {
      "$id": "/properties/filename_keys", 
      "type": "array", 
			"required": false,
      "items": {
        "$id": "/properties/filename_keys/items", 
        "type": "string", 
        "title": "filename keys", 
        "description": "Keys in the filename not captured by other fields", 
        "examples": [
          "task-rest",
					"acq-singleband",
					"bold",
					"T1w",
					"inplaneT2",
					"dwi"
        ]
      }
    }
  }
}

=== INCF/apine/examples/ds003.json
[
    {
        "dataset": "ds003",
        "participant": "01",
        "modality": "anat",
        "filename": "sub-01_inplaneT2.nii.gz",
        "filename_keys": [
            "inplaneT2"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "01",
        "modality": "anat",
        "filename": "sub-01_T1w.nii.gz",
        "filename_keys": [
            "T1w"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "01",
        "modality": "func",
        "filename": "sub-01_task-rhymejudgment_bold.nii.gz",
        "filename_keys": [
            "task-rhymejudgment",
            "bold"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "02",
        "modality": "anat",
        "filename": "sub-02_inplaneT2.nii.gz",
        "filename_keys": [
            "inplaneT2"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "02",
        "modality": "anat",
        "filename": "sub-02_T1w.nii.gz",
        "filename_keys": [
            "T1w"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "02",
        "modality": "func",
        "filename": "sub-02_task-rhymejudgment_bold.nii.gz",
        "filename_keys": [
            "task-rhymejudgment",
            "bold"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "03",
        "modality": "anat",
        "filename": "sub-03_inplaneT2.nii.gz",
        "filename_keys": [
            "inplaneT2"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "03",
        "modality": "anat",
        "filename": "sub-03_T1w.nii.gz",
        "filename_keys": [
            "T1w"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "03",
        "modality": "func",
        "filename": "sub-03_task-rhymejudgment_bold.nii.gz",
        "filename_keys": [
            "task-rhymejudgment",
            "bold"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "04",
        "modality": "anat",
        "filename": "sub-04_inplaneT2.nii.gz",
        "filename_keys": [
            "inplaneT2"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "04",
        "modality": "anat",
        "filename": "sub-04_T1w.nii.gz",
        "filename_keys": [
            "T1w"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "04",
        "modality": "func",
        "filename": "sub-04_task-rhymejudgment_bold.nii.gz",
        "filename_keys": [
            "task-rhymejudgment",
            "bold"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "05",
        "modality": "anat",
        "filename": "sub-05_inplaneT2.nii.gz",
        "filename_keys": [
            "inplaneT2"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "05",
        "modality": "anat",
        "filename": "sub-05_T1w.nii.gz",
        "filename_keys": [
            "T1w"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "05",
        "modality": "func",
        "filename": "sub-05_task-rhymejudgment_bold.nii.gz",
        "filename_keys": [
            "task-rhymejudgment",
            "bold"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "06",
        "modality": "anat",
        "filename": "sub-06_inplaneT2.nii.gz",
        "filename_keys": [
            "inplaneT2"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "06",
        "modality": "anat",
        "filename": "sub-06_T1w.nii.gz",
        "filename_keys": [
            "T1w"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "06",
        "modality": "func",
        "filename": "sub-06_task-rhymejudgment_bold.nii.gz",
        "filename_keys": [
            "task-rhymejudgment",
            "bold"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "07",
        "modality": "anat",
        "filename": "sub-07_inplaneT2.nii.gz",
        "filename_keys": [
            "inplaneT2"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "07",
        "modality": "anat",
        "filename": "sub-07_T1w.nii.gz",
        "filename_keys": [
            "T1w"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "07",
        "modality": "func",
        "filename": "sub-07_task-rhymejudgment_bold.nii.gz",
        "filename_keys": [
            "task-rhymejudgment",
            "bold"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "08",
        "modality": "anat",
        "filename": "sub-08_inplaneT2.nii.gz",
        "filename_keys": [
            "inplaneT2"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "08",
        "modality": "anat",
        "filename": "sub-08_T1w.nii.gz",
        "filename_keys": [
            "T1w"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "08",
        "modality": "func",
        "filename": "sub-08_task-rhymejudgment_bold.nii.gz",
        "filename_keys": [
            "task-rhymejudgment",
            "bold"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "09",
        "modality": "anat",
        "filename": "sub-09_inplaneT2.nii.gz",
        "filename_keys": [
            "inplaneT2"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "09",
        "modality": "anat",
        "filename": "sub-09_T1w.nii.gz",
        "filename_keys": [
            "T1w"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "09",
        "modality": "func",
        "filename": "sub-09_task-rhymejudgment_bold.nii.gz",
        "filename_keys": [
            "task-rhymejudgment",
            "bold"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "10",
        "modality": "anat",
        "filename": "sub-10_inplaneT2.nii.gz",
        "filename_keys": [
            "inplaneT2"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "10",
        "modality": "anat",
        "filename": "sub-10_T1w.nii.gz",
        "filename_keys": [
            "T1w"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "10",
        "modality": "func",
        "filename": "sub-10_task-rhymejudgment_bold.nii.gz",
        "filename_keys": [
            "task-rhymejudgment",
            "bold"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "11",
        "modality": "anat",
        "filename": "sub-11_inplaneT2.nii.gz",
        "filename_keys": [
            "inplaneT2"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "11",
        "modality": "anat",
        "filename": "sub-11_T1w.nii.gz",
        "filename_keys": [
            "T1w"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "11",
        "modality": "func",
        "filename": "sub-11_task-rhymejudgment_bold.nii.gz",
        "filename_keys": [
            "task-rhymejudgment",
            "bold"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "12",
        "modality": "anat",
        "filename": "sub-12_inplaneT2.nii.gz",
        "filename_keys": [
            "inplaneT2"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "12",
        "modality": "anat",
        "filename": "sub-12_T1w.nii.gz",
        "filename_keys": [
            "T1w"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "12",
        "modality": "func",
        "filename": "sub-12_task-rhymejudgment_bold.nii.gz",
        "filename_keys": [
            "task-rhymejudgment",
            "bold"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "13",
        "modality": "anat",
        "filename": "sub-13_inplaneT2.nii.gz",
        "filename_keys": [
            "inplaneT2"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "13",
        "modality": "anat",
        "filename": "sub-13_T1w.nii.gz",
        "filename_keys": [
            "T1w"
        ]
    },
    {
        "dataset": "ds003",
        "participant": "13",
        "modality": "func",
        "filename": "sub-13_task-rhymejudgment_bold.nii.gz",
        "filename_keys": [
            "task-rhymejudgment",
            "bold"
        ]
    }
]
